image:
  file: .gitpod.Dockerfile
ports:
  - port: 6080
    onOpen: open-preview
  - port: 5900
    onOpen: ignore
tasks:
  - before: sudo mkdir -p /home/barnacle/Qt && sudo chown -R gitpod:gitpod /home/barnacle && ([ -f "raster-draw.pro" ] && mv raster-draw.pro qt-raster-lines.pro)
    init:  pip install -U pip && pip install aqtinstall && aqt install-qt -O /home/barnacle/Qt linux desktop 6.1.3
    command: git config --global user.email $GIT_COMMITTER_EMAIL