name: Windows Release CI

on:
    push:
        branches: [main]
        paths:
            [
                "*.cpp",
                "*.ui",
                "*.h",
                "*.pro",
                "*.pri",
                ".github/workflows/windows.yml"
            ]
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v2
            - uses: ilammy/msvc-dev-cmd@v1
            - name: Cache Qt
              id: cache-qt
              uses: actions/cache@v1
              with:
                  path: "${{ github.workspace }}/qt/"
                  key: ${{ runner.os }}-Qt_cache
            - name: Install Qt
              uses: jurplel/install-qt-action@v2
              with:
                  version: "5.15.2"
                  host: "windows"
                  target: "desktop"
                  arch: "win64_msvc2019_64"
                  dir: "${{ github.workspace }}/qt/"
                  install-deps: "true"
                  modules: "qtcharts qtwebengine"
                  cached: ${{ steps.cache-qt.outputs.cache-hit }}
                  setup-python: "true"
                  tools: "tools_ifw,4.0.0,qt.tools.ifw.40 tools_qtcreator,4.13.2-0,qt.tools.qtcreator"

            - run: qmake --version
            - name: Run Qmake
              run: $Env:INCLUDE += ";${{ github.workspace }}/qt/Qt/5.15.2/msvc2019_64/include"; qmake
            - run: nmake
            - run: dir release
            - run: windeployqt -h
            - run: windeployqt --verbose 2 ${{ github.workspace }}/release/raster-draw.exe
            - run: dir
            - run: dir release
            - name: Upload a Build Artifact
              uses: actions/upload-artifact@v2.2.4
              with:
                  path: "release"
